name: Release 3X-UI for alpine
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build x-ui
      run: |
        mkdir app
        docker run -itd -e XRAY_VMESS_AEAD_FORCED=false --network=host --restart=unless-stopped --name 3x-ui ghcr.io/mhsanaei/3x-ui:latest
        docker cp 3x-ui:/app ./app
        docker cp 3x-ui:/usr/bin/x-ui ./app/x-ui.sh
    - name: Package
      run: tar -zcvf x-ui-linux-alpine.tar.gz ./app

    - name: Upload files to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: x-ui-linux-alpine
        path: x-ui-linux-alpine.tar.gz

    - name: Upload files to GH release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: x-ui-linux-alpine.tar.gz
        asset_name: x-ui-linux-alpine
        prerelease: true
